### ISSUE TITLE
Python3 operability

### ISSUE THREAD

**Issue by mgast-mpifr** [flomertens/wise#3]
Are there plans to make the software fit for python3? In wise itself I have fixed the errors of the print commands like

    File "/usr/local/bin/wise", line 20
    print USAGE

by simply changing the code  to

    print(USAGE)

But now I have the problem 

```
  Traceback (most recent call last):
    File "/usr/local/bin/wise", line 7, in <module>
      from wise import actions
    File "/usr/local/lib/python3.8/dist-packages/wise/__init__.py", line 1, in <module>
      from features import *
  ModuleNotFoundError: No module named 'features'.
```

Which in my estimation is because libwise is python2 only.

I installed it with pip3.

**Comment by etmeyer** [comment]
I realize it is 4 years later, but thanks to the magic of generative AI, I have made a working fork of this project in python 3.11. I will post a separate "issue" to advertise the link.
